_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.13.0
        t:
            "1":
                - 12
                - 45
                - 55
            "2":
                - 12
                - 45
                - 55
            "3":
                - 23
                - 55
            "4": 3.13.0
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": darwin-x86_64
