language: python

os:
  - linux
  - osx

python:
  - "3.8"
  - "3.9"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest

# command to run tests
script:
  pytest sim_transfer/tests

notifications:
  email:
    recipients:
      - jonas.rothfuss@inf.ethz.ch
    on_success: never
    on_failure: always

